import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Js Fundamentals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <nav>
          <ul>
            <Link href="/">
              <li>Home</li>
            </Link>

            <Link href="/store">
              <li>Store</li>
            </Link>
            
            <Link href="/category">
              <li>Category</li>
            </Link>
          </ul>
        </nav>
      </header>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
